# Data Preprocessing for Machine Learning

# Objectives
- Handle missing data (e.g., filling with mean/median, dropping).
- Encode categorical variables (e.g., using one-hot encoding or label encoding).
- Normalize or standardize numerical features.
- Split the dataset into training and testing sets.
- Tools: Python, pandas, scikit-learn.

In [10]:
# Import libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [11]:
# Load dataset
df = pd.read_csv('dataset/iris.csv')

# Inspect dataset
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
# Datatypes of the columns
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [13]:
# Check for missing values
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

There is not missing value in this dataset

In [14]:
# Check for duplicates
df.duplicated().sum()

np.int64(3)

In [15]:
# Drop duplicates 
df = df.drop_duplicates()

In [16]:
# Class distribution 
df["species"].value_counts()

species
versicolor    50
virginica     49
setosa        48
Name: count, dtype: int64

In [17]:
# Encoding categorical variables


# Initialize the encoder
encoder = OneHotEncoder(sparse_output=False, dtype=int)

# Fit and transform the specific column
encoded_species = encoder.fit_transform(df[["species"]])

# Create a DataFrame with the encoded values
df_encoded = pd.DataFrame(encoded_species, columns=encoder.get_feature_names_out(["species"]), index=df.index)

df = pd.concat([df.drop("species", axis=1), df_encoded], axis=1)

df.head()

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0

In [18]:
# 1. Standardize the numerical columns 
num_cols = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

df.head()

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,-0.915509,1.019971,-1.357737,-1.3357,1,0,0
1,-1.157560,-0.128082,-1.357737,-1.3357,1,0,0
2,-1.399610,0.331139,-1.414778,-1.3357,1,0,0
3,-1.520635,0.101529,-1.300696,-1.3357,1,0,0
4,-1.036535,1.249582,-1.357737,-1.3357,1,0,0

In [19]:
# Split the dataset into features and target variable
X = df[["sepal_length", "sepal_width", "petal_length", "petal_width"]]
y = df[["species_setosa", "species_versicolor", "species_virginica"]]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)   

# Check the sizes of your new datasets
print(f"Training set size: {X_train.shape[0]} rows")
print(f"Testing set size: {X_test.shape[0]} rows")

Training set size: 117 rows
Testing set size: 30 rows